name: "Latex - Generator"
author: "Michele DI Lecce"
description: "Generates and compile latex repository"
runs:
  using: "docker"
  image: "Dockerfile" # Use the pre-built image
branding:
  icon: "feather"
  color: "gray-dark"
inputs:
  email:
    description: The commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}